### ISSUE TITLE
No informations display

### ISSUE THREAD

**Issue by thmsaurel** [felixhageloh/pretty-weather#1]
Hi, I have an problem. I put my key in `index.coffee` but I doesn't have any informations on the widget.

``` coffee
apiKey: 'MY_APIKEY'
```

![screen shot 2015-03-19 at 12 08 43](https://cloud.githubusercontent.com/assets/5463836/6729257/c57b6ec0-ce30-11e4-8e7d-120975170dc9.png)
Any idea ?

**Comment by felixhageloh** [comment]
it could be that it is unable to find your location. Do you see any errors in the debug console?

**Comment by thmsaurel** [comment]
Great ! 
It was a location problem. I think I have enable location for ubersicht but instead not. 
Thanks, it's work now !
![screen shot 2015-03-19 at 12 28 13](https://cloud.githubusercontent.com/assets/5463836/6729522/6f4a5536-ce33-11e4-99f3-30ca2aa38a5b.png)

**Comment by felixhageloh** [comment]
:+1: Btw, to make the icons work, make sure you copy the entire widget folder and not to rename it (or if you do you also have to change the code)

**Comment by cabrinha** [comment]
fixed. turn on wifi.
